#pragma once

#include "arguments/Argument/Argument.h"

/**
 * ParserStatus is an enum whose members are used in the main-Method to catch errors.
 */
enum ParserStatus {
  Operation_Help, Operation_Simulation, Error_MissingArgument, Error_InvalidOperation,
};

/**
 * ArgumentParser is an extendable parser for arguments via commandline or configuration file.
 */
class ArgumentParser {
 public:

  /**
   * Destructor generated by the compiler.
   */
  virtual ~ArgumentParser() = default;

  /**
   * Validates the arguments via the argumentOptionIsAvailable-Method.
   * @return Member of enum ParserStatus, which is used in the main-Method to catch errors.
   */
  virtual ParserStatus validateInput() = 0;

  /**
   * Creates an Argument via the getValueOfArgumentOption-Method.
   * @return Constructor of Argument.
   */
  virtual Argument createArgument() = 0;

  /**
   * Prints the available flag-options.
   */
  virtual void showUsage() = 0;
};
