#pragma once

#include <optional>
#include <memory>
#include "Argument.h"
#include <tuple>

class ArgumentStatus {
 private:

  /**
   * Required arguments
   */
  std::tuple<bool, std::string, std::string> inputFileName;
  std::tuple<bool, std::string, double> end_time;
  std::tuple<bool, std::string, double> delta_t;

  /**
  * Optional arguments
  */

 public:
  ArgumentStatus();
  /**
   * Destructor generated by the compiler.
   */
  virtual ~ArgumentStatus() = default;

  std::tuple<bool, std::string, std::string> &getInputFileName();
  std::tuple<bool, std::string, double> &getEnd_time();
  std::tuple<bool, std::string, double> &getDelta_t();

  void setInputFileName(const std::string &flag, const std::string &value);
  void setEnd_time(const std::string &flag, const double &value);
  void setDelta_t(const std::string &flag, const double &value);

  bool validStatus();
};

/**
 * ArgumentParser is an extendable parser for arguments via commandline or configuration file.
 */
class ArgumentParser {
 protected:
  /**
  * Validates the arguments
  * @return bool
  */
  virtual bool validateInput() = 0;
 public:
  /**
   * Destructor generated by the compiler.
   */
  virtual ~ArgumentParser() = default;

  /**
   * Creates an Argument via the getValueOfArgumentOption-Method.
   * @return Argument.
   */
  virtual std::unique_ptr<Argument> createArgument() = 0;

  /**
   * Prints the available flag-options.
   */
  virtual void showUsage() = 0;
};
