#include "XYZWriter.h"
#include <sstream>
#include "particles/ParticleContainer.h"
#include <iomanip>

XYZWriter::XYZWriter(const std::string &file_name, const ParticleContainer &container) : OutputWriter(file_name,
                                                                                                      container) {};
XYZWriter::~XYZWriter() = default;

void XYZWriter::plotParticles(int iteration) {
  auto particles = container.getParticles();
  for (auto &p: particles) {
    Vector x = p.getX();
    file << "Ar ";
    file.setf(std::ios_base::showpoint);
    for (auto &xi: x) {
      file << xi << " ";
    }

    file << std::endl;
  }
}

void XYZWriter::writeFile(int iteration) {
  strStream << fileName << "_" << std::setfill('0') << std::setw(4) << iteration << ".xyz";
  file.open(strStream.str().c_str());
  file << container.getParticles().size() << std::endl;
  file << "Generated by MolSim. See http://openbabel.org/wiki/XYZ_(format) for "
          "file format doku."
       << std::endl;
  plotParticles(iteration);
  file.close();
}
