#include <string>
#include "particles/ParticleContainer.h"
#include "particles/Particle.h"

#pragma once

/**
 * OutputWriter is an extendable file writer for simulation states.
 */
class OutputWriter {
 public:

  /**
   * Constructs an OutputWriter to create files.
   * @param fileNameIn
   * @param pathIn
   * @param containerIn
   */
  OutputWriter(std::string fileNameIn, std::string pathIn, ParticleContainer &containerIn);

  /**
   * Destructor generated by the compiler.
   */
  virtual ~OutputWriter() = default;

  /**
   * Writes the information about the given iteration into the file.
   * @param iteration
   */
  virtual void writeFile(int iteration) = 0;
 protected:
  const std::string fileName;
  const std::string path;
  ParticleContainer &container;
};

