#include <string>
#include "particles/ParticleContainer.h"
#include "particles/Particle.h"
#include <utility>
#include <filesystem>

#pragma once

/**
 * OutputWriter is an extendable file writer for simulation states.
 */
template<size_t dim>
class OutputWriter {
 public:

  /**
   * Constructs an OutputWriter to create files.
   * @param pFileName
   * @param pPath
   * @param pContainer
   */
  OutputWriter(std::string pFileName, std::string pPath, ParticleContainer<dim> &pContainer) : fileName{
      std::move(pFileName)}, path{std::move(pPath)}, container{pContainer} {
    if (!std::filesystem::exists(path)) {
      std::filesystem::create_directory(path);
    }
  }

  /**
   * Destructor generated by the compiler.
   */
  virtual ~OutputWriter() = default;

  /**
   * Writes the information about the given iteration into the file.
   * @param iteration
   */
  virtual void writeFile(int iteration) = 0;
 protected:
  const std::string fileName;
  const std::string path;
  ParticleContainer<dim> &container;
};

