#include "outputWriter/XYZWriter.h"
#include <iomanip>
#include <sstream>
#include <particles/ParticleContainer.h>

namespace outputWriter {

XYZWriter::XYZWriter() = default;

XYZWriter::~XYZWriter() = default;

void XYZWriter::plotParticles(const ParticleContainer& particleContainer,
                              const std::string &filename, int iteration) {
  std::ofstream file;
  std::stringstream strstr;
  strstr << filename << "_" << std::setfill('0') << std::setw(4) << iteration << ".xyz";
  auto particles = particleContainer.getParticles();
  file.open(strstr.str().c_str());
  file << particles.size() << std::endl;
  file << "Generated by MolSim. See http://openbabel.org/wiki/XYZ_(format) for "
          "file format doku."
       << std::endl;

  for (auto &p : particles) {
    Vector x = p.getX();
    file << "Ar ";
    file.setf(std::ios_base::showpoint);

    for (auto &xi : x) {
      file << xi << " ";
    }

    file << std::endl;
  }

  file.close();
}

} // namespace outputWriter
