#include "Particle.h"

#include <iostream>
#include <spdlog/spdlog.h>
#include "utils/ArrayUtils.h"

//---------------------------Constructor---------------------------
Particle::Particle(int type_arg) : x{}, v{}, f{}, old_f{}, m{}, type{type_arg} {
  // SPDLOG_INFO("Particle generated");
}

Particle::Particle(const Particle &other) : x{other.x}, v{other.v}, f{other.f}, old_f{other.old_f}, m{other.m},
                                            type{other.type} {
  // SPDLOG_INFO("Particle generated by copy");
}

Particle::Particle(const Vector &x_arg, const Vector &v_arg, double m_arg, int type_arg) : x{x_arg}, v{v_arg}, f{},
                                                                                           old_f{}, m{m_arg},
                                                                                           type{type_arg} {
  // SPDLOG_INFO("Particle generated");
}

Particle::~Particle() {
  // SPDLOG_INFO("Particle destructed");
}

//---------------------------Getter and Setter---------------------------

const Vector &Particle::getX() const { return x; }

const Vector &Particle::getV() const { return v; }

const Vector &Particle::getF() const { return f; }

const Vector &Particle::getOldF() const { return old_f; }

double Particle::getM() const { return m; }

int Particle::getType() const { return type; }

void Particle::setX(const Vector &position) { x = position; }

void Particle::setV(const Vector &velocity) { v = velocity; }

void Particle::setF(const Vector &force) { f = force; }

void Particle::setOldF(const Vector &oldForce) { old_f = oldForce; }

//---------------------------Methods---------------------------

std::string Particle::toString() const {
  std::stringstream stream;
  stream << "Particle: X:" << x << " v: " << v << " f: " << f << " old_f: " << old_f << " type: " << type;
  return stream.str();
}

bool Particle::operator==(const Particle &other) {
  return (x == other.x) and (v == other.v) and (f == other.f) and (type == other.type) and (m == other.m)
      and (old_f == other.old_f);
}
void Particle::updateForce(const Vector &force) {
  f += force;
}

std::ostream &operator<<(std::ostream &stream, const Particle &p) {
  stream << p.toString();
  return stream;
}
