#pragma once

#include "Particle.h"
#include <vector>

/**
 * ParticleContainer is a container for particles that provides functions to iterate over single particles and pairs.
 */
template<size_t dim>
class ParticleContainer {
 private:

  /**
   * Particles-Vector Stores all particles.
   */
  std::vector<Particle<dim>> particles;

 public:

  /**
   * Default Constructor.
   */
  ParticleContainer() = default;

  /**
   * Default Destructor.
   */
  virtual ~ParticleContainer() = default;

  /**
   * Constructs a ParticleContainer from the provided vector of particlesIn.
   * @param pParticles
   */
  explicit ParticleContainer(std::vector<Particle<dim>> pParticles) : particles{std::move(pParticles)} {
    SPDLOG_TRACE("ParticleContainer generated");
  }

  /**
   * Copy Constructor generated by the compiler.
   * @param particleContainer
   */
  ParticleContainer(const ParticleContainer &particleContainer) = default;

  /**
   * Adds the particle to the ParticleContainer.
   * @param p The particle to be added.
   */
  void addParticle(Particle<dim> p) {
    particles.push_back(std::move(p));
  }

  [[nodiscard]] std::vector<Particle<dim>> &getParticles() {
    return particles;
  }

  /**
   * @return Size of the particle-Vector.
   */
  [[nodiscard]] unsigned long size() const {
    return particles.size();
  }

  /**
   * @return Iterator to the beginning of the particles-Vector.
   */
  [[nodiscard]] auto begin() { return particles.begin(); }

  /**
   * @return Iterator to the end of the particles-Vector.
   */
  [[nodiscard]] auto end() { return particles.end(); }

  /**
 * Operator that allows mutable member access.
 * @param i Index for member access.
 * @return
 */
  Particle<dim> &operator[](unsigned long i) {
    return particles[i];
  }

  /**
   * Operator that allows immutable member access.
   * @param i Index for member access.
   * @return
   */
  Particle<dim> operator[](unsigned long i) const {
    return particles[i];
  }
};