name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ g++, clang ]

    steps:
      - uses: actions/checkout@v2

      - name: Install Xerces
        run: sudo apt-get install libxerces-c-dev

      - name: Install cppcheck
        run: sudo apt-get install cppcheck

      - name: Run cppcheck
        run: cppcheck --enable=style --enable=performance ${{github.workspace}}/src

      - name: Create Build Directory
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Run cmake
        run: cmake .. -DBUILD_DOCUMENTATION=ON
        working-directory: ${{github.workspace}}/build

      - name: Run make
        run: make
        working-directory: ${{github.workspace}}/build
        env:
          CC: ${{ matrix.compiler }}

      # Optional add tests

