name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Xerces
        run: sudo apt install libxerces-c-dev

      - name: Create Build Directory
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Run cmake
        run: cmake .. -DBUILD_DOCUMENTATION=ON
        working-directory: ${{github.workspace}}/build

      - name: Run make
        run: make
        working-directory: ${{github.workspace}}/build

      # Optional add tests

