name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        compiler: [ [ gcc, g++ ], [ clang, clang++ ] ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Xerces
        run: sudo apt-get install libxerces-c-dev

      - name: Make build dir
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Run cmake
        run: cmake .. -D BUILD_DOCUMENTATION=OFF -D BUILD_TESTS=OFF -D CMAKE_C_COMPILER=${{ matrix.compiler[0] }} -D CMAKE_CXX_COMPILER=${{ matrix.compiler[1] }}
        working-directory: ${{github.workspace}}/build
        env:
          CC: ${{ matrix.compiler[0] }}
          CXX: ${{ matrix.compiler[1] }}

      - name: Run make
        run: make
        working-directory: ${{github.workspace}}/build

      - name: Run make clean to remove build folder
        run: make clean

  cppcheck:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Install cppcheck
        run: sudo apt-get install cppcheck

      - name: Run cppcheck
        run: cppcheck --enable=style --enable=performance ${{github.workspace}}/src

  testing:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: GCC 10
        run: |
          sudo apt update
          sudo apt install gcc-10 g++-10
        shell: bash

      - name: Install Xerces
        run: sudo apt-get install libxerces-c-dev

      - name: Make build dir
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Run cmake
        run: cmake .. -D BUILD_DOCUMENTATION=OFF -D BUILD_TESTS=OFF -D CMAKE_C_COMPILER=gcc-10 -D CMAKE_CXX_COMPILER=g++-10
        working-directory: ${{github.workspace}}/build
        env:
          CC: gcc-10
          CXX: g++-10

      - name: Run make
        run: make
        working-directory: ${{github.workspace}}/build

      - name: Run CTest
        run: ctest
        working-directory: ${{github.workspace}}/build
