name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Xerces
        run: sudo apt-get install libxerces-c-dev

      - name: Use makefile to prepare and run cmake
        run: make
        env:
          CC: clang
          CXX: clang++

      - name: Run make
        run: make
        working-directory: ${{github.workspace}}/build

      - name: Run make clean to remove build folder
        run: make clean

  cppcheck:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Install cppcheck
        run: sudo apt-get install cppcheck

      - name: Run cppcheck
        run: cppcheck --enable=style --enable=performance ${{github.workspace}}/src

  testing:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Install test environement (1/2)
        run: |
          sudo apt-get install libxerces-c-dev
          cmake -E make_directory ${{github.workspace}}/build

      - name: Install test environement (2/2)
        run: |
          cmake .. -DBUILD_DOCUMENTATION=ON
          make
        working-directory: ${{github.workspace}}/build
        env:
          CC: clang
          CXX: clang++

      - name: Run CTest
        run: ctest